### ISSUE TITLE
Admin user can create, read, update and delete students in class

### ISSUE THREAD

**Issue by Tresha-Gaye** [tcampbell01/Citizenship-community#2]
User Stories

As the admin user, I can create my own profile that stores information about me

As the admin user, I can create new classes that provide access to a group of users

As the admin user, I can add users to a class by creating new, unique user profiles that store information about the user

As the admin user, I can retrieve my profile data or another user's profile data

As the admin user, I can update my profile data or another user's profile data

As the admin user, I can delete my profile or another user's profile data

**Comment by tcampbell01** [comment]
Tabling for now in effort to reach MVP
